[formatter.typos]
command = "typos"
options = ["--write-changes", "--force-exclude"]
includes = ["*"]
excludes = [
  "*.kicad_*",
  "pcb/.gitignore",
]

[formatter.markdown]
command = "mdl"
includes = [ "*.md" ]

[formatter.nix]
command = "alejandra"
includes = [ "*.nix" ]

[formatter.rust]
command = "rustfmt"
options = ["--edition", "2024"]
includes = [ "*.rs" ]
